# Generated by Django 4.2.5 on 2023-10-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='nota3',
            field=models.IntegerField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='notas',
            name='nota1',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='notas',
            name='nota2',
            field=models.IntegerField(default=0, max_length=500),
        ),
    ]
