# Generated by Django 4.2.5 on 2023-10-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_notas_nota3_alter_notas_nota1_alter_notas_nota2'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='defi',
            field=models.IntegerField(default=0, max_length=500),
        ),
    ]
