# Generated by Django 4.2.5 on 2023-11-15 00:59

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_students_id_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id_person',
            field=models.IntegerField(null=True, verbose_name=students.models.User),
        ),
    ]
