# Generated by Django 4.2.5 on 2023-11-15 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_students_id_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
