# Generated by Django 4.2.5 on 2023-11-15 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_delete_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cities',
        ),
        migrations.DeleteModel(
            name='countries',
        ),
        migrations.DeleteModel(
            name='departaments',
        ),
        migrations.DeleteModel(
            name='identification_types',
        ),
        migrations.DeleteModel(
            name='persons',
        ),
    ]
